### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by iflowingwater** [trazyn/ieaseMusic#115]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:581:26)

V1.1.1中出现，一天之内出现好几次，然后就暂停播放了。 V1.1.0没有碰到。

**Comment by iflowingwater** [comment]
A JavaScript error occurred in the main process

Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)

**Comment by kugoo** [comment]
不是暂停播放，从1.1.0到1.1.2都无法播放，点了自己关联云音乐账户最喜欢的音乐以后，一直是转圈圈，一片白板，无法使用，点推荐歌单也是一样的效果

**Comment by trazyn** [comment]
@kugoo 更新后要删除下原来的Cookie文件
```
rm -rf ~/Library/Application\ Support/iease-music/
```
