### ISSUE TITLE
Mac客户端--一直在加载，从来没进去过。。。

### ISSUE THREAD

**Issue by beyond510** [trazyn/ieaseMusic#133]
版本1.1.2   就是一直在转圈儿，Plaese Wait...怎么办？
<img width="740" alt="wx20180129-112341 2x" src="https://user-images.githubusercontent.com/28379540/35492267-e31d52aa-04e6-11e8-9fe7-c5c96f119b0b.png">

**Comment by trazyn** [comment]
报错信息看看

**Comment by beyond510** [comment]
没弹出报错信息啊，就是这么一直加载着

**Comment by trazyn** [comment]
alt+cmd+i 看看控制台的输出

**Comment by oxdc** [comment]
Ubuntu 下相同错误，控制台显示

```
app.0c23804….js?0c23804…:23 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at A.<anonymous> (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:23:55225)
    at g (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:62830)
    at Generator._invoke (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:63949)
    at Generator.A.(anonymous function) [as next] (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:63009)
    at g (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:23:53386)
    at file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:23:53533
    at Promise (<anonymous>)
    at A.<anonymous> (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:23:53330)
    at A.i.value (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:23:55364)
    at r (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:10:20905)
(anonymous) @ app.0c23804….js?0c23804…:23
g @ app.0c23804….js?0c23804…:447
(anonymous) @ app.0c23804….js?0c23804…:447
A.(anonymous function) @ app.0c23804….js?0c23804…:447
g @ app.0c23804….js?0c23804…:23
(anonymous) @ app.0c23804….js?0c23804…:23
(anonymous) @ app.0c23804….js?0c23804…:23
i.value @ app.0c23804….js?0c23804…:23
r @ app.0c23804….js?0c23804…:10
M @ app.0c23804….js?0c23804…:10
(anonymous) @ app.0c23804….js?0c23804…:447
g @ app.0c23804….js?0c23804…:447
(anonymous) @ app.0c23804….js?0c23804…:447
A.(anonymous function) @ app.0c23804….js?0c23804…:447
g @ app.0c23804….js?0c23804…:447
(anonymous) @ app.0c23804….js?0c23804…:447
app.0c23804….js?0c23804…:447 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at A.<anonymous> (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:18012)
    at g (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:62830)
    at Generator._invoke (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:63949)
    at Generator.A.(anonymous function) [as next] (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:63009)
    at g (file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:16144)
    at file:///opt/ieaseMusic/resources/app.asar/app.0c238040cb531ec4e79e.js?0c238040cb531ec4e79e:447:16244
    at <anonymous>
```

**Comment by oxdc** [comment]
出现了一个报错弹窗

```
Uncaught Exception:
Error: listen EADDRINUSE :::10086
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Function._.listen (/opt/ieaseMusic/resources/app.asar/main.js:355:4483)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:123564
    at /opt/ieaseMusic/resources/app.asar/main.js:294:137981
    at o (/opt/ieaseMusic/resources/app.asar/main.js:294:157105)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:139262
    at /opt/ieaseMusic/resources/app.asar/main.js:294:134940
    at n (/opt/ieaseMusic/resources/app.asar/main.js:294:157052)
    at o (/opt/ieaseMusic/resources/app.asar/main.js:294:157132)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:139262
    at /opt/ieaseMusic/resources/app.asar/main.js:294:134828
    at tryToString (fs.js:449:3)
```

**Comment by trazyn** [comment]
第一个是账号下没有推荐歌单，登录到官网点下每日推荐就好，第二个报错是端口被占用了，应该是重复开启了

**Comment by oxdc** [comment]
刚刚重新安装（已清除 `~/.config` 中对应的文件）并重新登录，就没有问题。第一个问题的解决方法还没测试，目前一切正常。不过一定要手动点击一次每日推荐？是否有其他解决方案？

**Comment by trazyn** [comment]
不需要每次点，激活一下就好

**Comment by 0xJacky** [comment]
重新登录的时候报错
```Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at /Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:459:194252
    at IncomingMessage.<anonymous> (/Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:7:748)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by beyond510** [comment]
我提这个问题的时候是1.1.2  我今天更新到了1.1.5这个问题还是存在。
控制台里没内容,10083端口没有其它占用。
<img width="738" alt="wx20180524-165848 2x" src="https://user-images.githubusercontent.com/28379540/40475270-c18d63e0-5f73-11e8-8dad-ffe887f0a2a0.png">
