### ISSUE TITLE
無法登入

### ISSUE THREAD

**Issue by rexx0520** [trazyn/ieaseMusic#135]
在 mac 上用手機號無法登入
您登出後再登入試試
我看 http://localhost:10086/api/home/122645768 確實能看到我的帳號的歌單的

**Comment by trazyn** [comment]
登录报错了？

**Comment by rexx0520** [comment]
沒有報錯，就hang在logining不動
開發者工具裡有報錯 有東西是 undefined

**Comment by trazyn** [comment]
开发者工具里面的内容看看

**Comment by hrzhao76** [comment]
错误代码：
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at /Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:459:194252
    at IncomingMessage.<anonymous> (/Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:7:748)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by trazyn** [comment]
@hrzhao76 登录时候控制台的错误么？

**Comment by hrzhao76** [comment]
@trazyn  是的。 登陆的时候提示的错误。

**Comment by rexx0520** [comment]
我的顯示的是
Uncaught (in promise) TypeError: Cannot read property 'data' of undefined
    at I.value (app.0c23804….js?0c23804…:484)
    at Object.U [as allowStateChanges] (app.0c23804….js?0c23804…:10)
    at app.0c23804….js?0c23804…:10
    at MI (app.0c23804….js?0c23804…:10)
    at A.track (app.0c23804….js?0c23804…:23)
    at I.T [as render] (app.0c23804….js?0c23804…:10)
    at s._renderValidatedComponentWithoutOwnerOrContext (app.0c23804….js?0c23804…:447)
    at s._renderValidatedComponent (app.0c23804….js?0c23804…:447)
    at s._updateRenderedComponent (app.0c23804….js?0c23804…:447)
    at s._performComponentUpdate (app.0c23804….js?0c23804…:447)

**Comment by trazyn** [comment]
@rexx0520 看不出来具体是什么问题，要登录你的账号看看具体是什么问题

**Comment by upupzhao** [comment]
一直显示登陆页面，并且打开以后点击登陆没有反应
