### ISSUE TITLE
ubuntu 17 bug~~~~~打醒你

### ISSUE THREAD

**Issue by gongroc** [trazyn/ieaseMusic#140]
1.无法关闭音乐。窗口关掉了但还是继续播放中。。
2.多打开几个音乐之后，每个都在播～～～
3.重新打开客户端后爆错。

`Uncaught Exception:
Error: listen EADDRINUSE :::10086
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Function._.listen (/opt/ieaseMusic/resources/app.asar/main.js:355:4483)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:123564
    at /opt/ieaseMusic/resources/app.asar/main.js:294:137981
    at o (/opt/ieaseMusic/resources/app.asar/main.js:294:157105)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:139262
    at /opt/ieaseMusic/resources/app.asar/main.js:294:134940
    at n (/opt/ieaseMusic/resources/app.asar/main.js:294:157052)
    at o (/opt/ieaseMusic/resources/app.asar/main.js:294:157132)
    at /opt/ieaseMusic/resources/app.asar/main.js:294:139262
    at /opt/ieaseMusic/resources/app.asar/main.js:294:134828
    at tryToString (fs.js:449:3)`

**Comment by mountainguan** [comment]
ubuntu 18.04也一样,而且快捷键没有效果

**Comment by iSenninha** [comment]
囧--，我怎么觉得不好用。。。

**Comment by JasonLuo5** [comment]
ubuntu 18.04 启动也报错

**Comment by trazyn** [comment]
需要API部分加入到主线程

**Comment by wewall** [comment]
打开了,开源开发不易,李姐万岁

**Comment by trazyn** [comment]
1 #138
