### ISSUE TITLE
archlinux  ， node -v v9.6.1

### ISSUE THREAD

**Issue by yueduz** [trazyn/ieaseMusic#143]
![2018-02-26 18-53-09](https://user-images.githubusercontent.com/1448159/36666685-596daf86-1b26-11e8-9bbe-0c0ce3115a54.png)

```
Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at /opt/ieaseMusic/resources/app.asar/main.js:459:194252
    at IncomingMessage.<anonymous> (/opt/ieaseMusic/resources/app.asar/main.js:7:748)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9
```

**Comment by trazyn** [comment]
目测是账号没有日推歌单，需要登录到网易云音乐点下日推歌单

**Comment by trazyn** [comment]
Close #172
