### ISSUE TITLE
打开一直初始化

### ISSUE THREAD

**Issue by FateLight** [trazyn/ieaseMusic#150]
系统：macOS 10.3.3 最新

**Comment by trazyn** [comment]
控制台有没报错啊

**Comment by FateLight** [comment]
打开应用，一直卡在Please Wait

**Comment by trazyn** [comment]
具体错误可以cmd+shift+i 在控制台查看的

**Comment by CaptainYukinoshitaHachiman** [comment]
我这里有相同现象，控制台内容如下：
```
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at A.value (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2466054)
    at R (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:93010)
    at A.M (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:92614)
    at A.<anonymous> (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2476291)
    at u (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2525772)
    at Generator._invoke (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2525560)
    at Generator.A.(anonymous function) [as next] (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2525951)
    at t (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2475053)
    at file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.4866a46fcb9e36ee4e93.js?4866a46fcb9e36ee4e93:1:2475147
    at <anonymous>
```

**Comment by giihuber** [comment]
江苏苏州电信宽带一直Please Wait过不去，Mac连接手机网络就能使用。
Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at A.value (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:7455)
    at r (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:10:20905)
    at A.M (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:10:20790)
    at A.<anonymous> (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:17750)
    at g (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:62830)
    at Generator._invoke (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:63949)
    at Generator.A.(anonymous function) [as next] (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:63009)
    at g (file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:16144)
    at file:///Applications/ieaseMusic.app/Contents/Resources/app.asar/app.f97ba19f8d767bdb16fe.js?f97ba19f8d767bdb16fe:447:16244
    at <anonymous>

**Comment by giihuber** [comment]
苏州电信，更换一下猫网络设置（改为动态IP连接，好像是这个）就能用了

**Comment by zhengjun131461** [comment]
linux mint 东莞移动
(node:4814) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:4814) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at /opt/ieaseMusic/resources/app.asar/main.js:621:278642
    at w (/opt/ieaseMusic/resources/app.asar/main.js:251:71469)
    at Generator._invoke (/opt/ieaseMusic/resources/app.asar/main.js:251:71257)
    at Generator.e.(anonymous function) [as next] (/opt/ieaseMusic/resources/app.asar/main.js:251:71648)
    at r (/opt/ieaseMusic/resources/app.asar/main.js:621:277664)
    at /opt/ieaseMusic/resources/app.asar/main.js:621:277758
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4814) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4814) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
