### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Lucas0625** [trazyn/ieaseMusic#155]
运行环境：macOS 10.13.1
ieaseMusic版本：1.1.4
当电脑没有网络连接时 会不断弹出这个报错界面。
<img width="420" alt="default" src="https://user-images.githubusercontent.com/35127185/38009367-9893a1bc-3286-11e8-8292-877eaa8633b0.png">

**Comment by lawrencehjf** [comment]
Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at /xx/ieaseMusic.app/Contents/Resources/app.asar/main.js:565:194428
    at IncomingMessage.<anonymous> (/x/ieaseMusic.app/Contents/Resources/app.asar/main.js:8:743)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by zxeoc** [comment]
跟@lawrencehjf 一样，系统：Linux Mint 18.3

**Comment by trazyn** [comment]
@dhqdqk @zxeoc @lawrencehjf  #172
