### ISSUE TITLE
macOS版本无法登录

### ISSUE THREAD

**Issue by lazybri** [trazyn/ieaseMusic#158]
在下使用的是macOS10.10，版本1.1.4，输入手机号和密码后弹出一个错误窗口，无法登录，并且一进去软件就自动播放音乐。

**Comment by lazybri** [comment]
在下还是乖乖使用mysic.163.com网页版先，望修复，UserInterface设计给赞一个。

**Comment by JohnsonBob** [comment]
Mac10.13.5
A JavaScript error occurred in the main process

**Comment by JohnsonBob** [comment]
Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at /Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:565:194428
    at IncomingMessage.<anonymous> (/Applications/ieaseMusic.app/Contents/Resources/app.asar/main.js:8:743)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by JohnsonBob** [comment]
进去自动播放“2002年的第一场雪”每次都是

**Comment by trazyn** [comment]
登录要用手机号！登录要用手机号！登录要用手机号！

Close #172

**Comment by CipherN** [comment]
> 登录要用手机号！登录要用手机号！登录要用手机号！
> 
> Close #172

macos 10.13.6，手机号、微信扫码均无法登陆
