### ISSUE TITLE
Ubuntu 18.04 无法启动，一直在转圈，强行关闭后，会报若干错误

### ISSUE THREAD

**Issue by JasonLuo5** [trazyn/ieaseMusic#169]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)

**Comment by trazyn** [comment]
接口越来越封闭了，看起来是连接问题

**Comment by eecshope** [comment]
同ubuntu18.04
A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by trazyn** [comment]
看起来是高频访问限制可以尝试按照RaeADME修改hosts unblock
