### ISSUE TITLE
第一次打开正常使用，中途卡死，然后就用不了了

### ISSUE THREAD

**Issue by wsszh** [trazyn/ieaseMusic#195]
重新安装后，打开一直停留在加载界面，并且有报错：

Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by trazyn** [comment]
通常是访问被限制，可以尝试改下`Host`
https://github.com/acgotaku/NetEaseMusicWorld

**Comment by trazyn** [comment]
Chrome 商店也有很多国内的`Unblock`插件，可以从插件里面找出那些代理，我在国外用的就是这些插件里面的代理（怎么找就不说了，不太道德）

**Comment by wsszh** [comment]
改了hosts文件后，还是不行... @trazyn
