### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by teemola** [trazyn/ieaseMusic#258]
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:554:12)

 system operation： mac high sierra 10.13.6

**Comment by trazyn** [comment]
参考 unblock
