### ISSUE TITLE
Mac 客户端无法打开

### ISSUE THREAD

**Issue by palooney** [trazyn/ieaseMusic#264]
Mac客户端安装后一直在 loading，一段时间后显示如下错误
`Uncaught Exception:
Error: connect ETIMEDOUT 45.32.72.192:80
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)`

**Comment by trazyn** [comment]
https://github.com/trazyn/ieaseMusic#unblock
