### ISSUE TITLE
Error: Cannot find module '../NeteaseCloudMusicApi/router/album'

### ISSUE THREAD

**Issue by anuxs** [trazyn/ieaseMusic#30]
下载源码，npm install ，然后 npm run dev 报错。
已经单独安装了 NeteaseCloudMusicApi/

ieaseMusic git:(master) ✗ npm run dev

> iease-music@0.0.3 dev /Users/langge/dev/test/h5js/webtest/ieaseMusic
> concurrently --kill-others "npm run hot-server" "npm run start-hot"

[0] 
[0] > iease-music@0.0.3 hot-server /Users/langge/dev/test/h5js/webtest/ieaseMusic
[0] > cross-env NODE_ENV=development DEBUG_COLORS=true DEBUG=dev:*,-not_this node -r babel-register server/dev.js
[0] 
[1] 
[1] > iease-music@0.0.3 start-hot /Users/langge/dev/test/h5js/webtest/ieaseMusic
[1] > cross-env HOT=1 NODE_ENV=development DEBUG_COLORS=true DEBUG=dev:*,-not_this ./node_modules/.bin/electron -r babel-register -r babel-polyfill ./main
[1] 
[1] App threw an error during load
[1] Error: Cannot find module '../NeteaseCloudMusicApi/router/album'
[1]     at Module._resolveFilename (module.js:485:15)
[1]     at Function.Module._resolveFilename (/Users/langge/dev/test/h5js/webtest/ieaseMusic/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
[1]     at Function.Module._load (module.js:437:25)
[1]     at Module.require (module.js:513:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (/Users/langge/dev/test/h5js/webtest/ieaseMusic/server/api.js:20:19)
[1]     at Object.<anonymous> (/Users/langge/dev/test/h5js/webtest/ieaseMusic/server/api.js:271:3)
[1]     at Module._compile (module.js:569:30)
[1]     at loader (/Users/langge/dev/test/h5js/webtest/ieaseMusic/node_modules/babel-register/lib/node.js:144:5)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/langge/dev/test/h5js/webtest/ieaseMusic/node_modules/babel-register/lib/node.js:154:7)
[0]   dev:server Hot reload server is running with port 3001 👏 +0ms
[0] webpack built 769dcd0f1da913797c5a in 11987ms
[0] Hash: 769dcd0f1da913797c5a
[0] Version: webpack 3.6.0
[0] Time: 11987ms
[0]     Asset     Size  Chunks                    Chunk Names
[0] bundle.js  15.4 MB       0  [emitted]  [big]  main
[0]   [13] (webpack)/buildin/module.js 517 bytes {0} [built]
[0]   [26] ./node_modules/react-jss/lib/index.js 1.5 kB {0} [built]
[0]   [32] ./node_modules/mobx-react/index.module.js 34.6 kB {0} [built]
[0]   [35] ./node_modules/react-router/es/index.js 1.46 kB {0} [built]
[0]   [95] external "electron" 42 bytes {0} [not cacheable]
[0]  [112] ./src/js/stores/controller.js 19.6 kB {0} [built]
[0]  [210] ./node_modules/react-dom/index.js 59 bytes {0} [built]
[0]  [575] multi webpack-hot-middleware/client?path=http://localhost:3001/__webpack_hmr babel-polyfill ./src/app.js 52 bytes {0} [built]
[0]  [576] (webpack)-hot-middleware/client.js?path=http://localhost:3001/__webpack_hmr 7.04 kB {0} [built]
[0]  [586] ./node_modules/babel-polyfill/lib/index.js 833 bytes {0} [built]
[0]  [788] ./src/app.js 12.2 kB {0} [built]
[0] [1062] ./node_modules/ionicons201/css/ionicons.css 969 bytes {0} [built]
[0] [1067] ./src/global.css 1 kB {0} [built]
[0] [1068] ./src/js/utils/albumColors.js 5.88 kB {0} [built]
[0] [1111] ./src/js/routes.js 2.6 kB {0} [built]
[0]     + 1269 hidden modules
[0] webpack: Compiled successfully.

**Comment by trazyn** [comment]
需要安装子模块 参考readme
