### ISSUE TITLE
Ubuntu18.04无法运行

### ISSUE THREAD

**Issue by catror** [trazyn/ieaseMusic#341]
```
(gdb) bt
#0  0x0000000004b4b984 in accelerator_util::GenerateAcceleratorTable(std::__1::map<ui::Accelerator, accelerator_util::MenuItem, std::__1::less<ui::Accelerator>, std::__1::allocator<std::__1::pair<ui::Accelerator const, accelerator_util::MenuItem> > >*, atom::AtomMenuModel*) ()
#1  0x0000000004b49c95 in atom::RootView::RegisterAcceleratorsWithFocusManager(atom::AtomMenuModel*) ()
#2  0x0000000004b31f7b in atom::NativeWindowViews::SetMenu(atom::AtomMenuModel*) ()
#3  0x0000000004b1a015 in atom::api::TopLevelWindow::SetMenu(v8::Isolate*, v8::Local<v8::Value>) ()
#4  0x0000000004afbacb in mate::internal::Dispatcher<void (atom::api::TopLevelWindow*, v8::Isolate*, v8::Local<v8::Value>)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) ()
#5  0x00007ffff6f5accc in  () at /opt/ieaseMusic/libnode.so
#6  0x00007ffff6fac0c5 in  () at /opt/ieaseMusic/libnode.so
#7  0x00007ffff6fab799 in  () at /opt/ieaseMusic/libnode.so
```

**Comment by catror** [comment]
.Appimage格式的包有同样的问题
