### ISSUE TITLE
[Ubuntu 16.04]Socket hang up error

### ISSUE THREAD

**Issue by Awesomepig** [trazyn/ieaseMusic#36]
Version: 0.0.4-linux-amd64.deb
OS: ubuntu 16.04 x64
Error :
> Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Screen : 
![2017-10-11 17-42-19](https://user-images.githubusercontent.com/6083234/31433344-9565f9ea-aeab-11e7-8af7-316348b4669c.png)

多谢.

**Comment by trazyn** [comment]
参考 #10 改下hosts 就好了

**Comment by trazyn** [comment]
错了是 #20

**Comment by Awesomepig** [comment]
谢谢

**Comment by trazyn** [comment]
客气
