### ISSUE TITLE
problem: Linux版本（Ubuntu/Debian）无法打开

### ISSUE THREAD

**Issue by leslievan** [trazyn/ieaseMusic#43]
> System Version: Ubuntu 17.04

---

无法进入应用，显示错误信息如下
`A JavaScript error occurred in the main process`
`Uncaught Exception:
Error: listen EADDRINUSE :::10086
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Function.j.listen (/opt/ieaseMusic/resources/app.asar/main.js:251:4482)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:124889
    at /opt/ieaseMusic/resources/app.asar/main.js:234:140845
    at i (/opt/ieaseMusic/resources/app.asar/main.js:234:159903)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:142126`

然后就出现了一个圆圈一直转，还有一行彩蛋

**Comment by chy9002** [comment]
mac也无法进入, 终端显示:
2017-10-18 13:41:42.724 ieaseMusic[65020:5846321] *** WARNING: Textured window <AtomNSWindow: 0x7fe46ccd8410> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.

**Comment by trazyn** [comment]
第一个是端口被占用参考#20 第二个是警告不是error 猜测是hosts问题参考#20

**Comment by trazyn** [comment]
第一个参考#40

**Comment by chy9002** [comment]
尝试修改hosts后还是无法进入

<img width="1424" alt="2017-10-18 13 59 17" src="https://user-images.githubusercontent.com/7344772/31702938-b01543f6-b39f-11e7-95e6-89d8f48714cf.png">

**Comment by trazyn** [comment]
@chy9002 现在基本都没有高频调用的限制了，国内都可以不用改hosts 了，这个情况要看看devtools里面的请求是否正常

**Comment by chy9002** [comment]
@trazyn 

```
localhost:10086/login/refresh Failed to load resource: net::ERR_EMPTY_RESPONSE
app.2bf2b35af22ff56042b0.js:42 Uncaught (in promise) Error: Network Error
    at A.exports (app.2bf2b35af22ff56042b0.js:42)
    at XMLHttpRequest.a.onerror (app.2bf2b35af22ff56042b0.js:454)
```

**Comment by trazyn** [comment]
@chy9002 国内的话去掉那个hosts再看看，现在基本没碰到过高频调用的限制

**Comment by chy9002** [comment]
我已经去掉了hosts, 还是会有一样的错误.

**Comment by trazyn** [comment]
改了hosts或者直连都不行的话，那估计就是ISP有限制了

**Comment by catbaron0** [comment]
ISP是限制什么？

**Comment by trazyn** [comment]
@catbaron0 你的网络提供商，XX野鸡宽带

**Comment by catbaron0** [comment]
ISP还会限制网易云的流量么?

**Comment by trazyn** [comment]
直连代理都连不上那就没办法了
