### ISSUE TITLE
无法正常显示图片

### ISSUE THREAD

**Issue by zhanjw** [trazyn/ieaseMusic#55]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE :::10086
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Function.j.listen (/opt/ieaseMusic/resources/app.asar/main.js:251:4482)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:124889
    at /opt/ieaseMusic/resources/app.asar/main.js:234:140845
    at i (/opt/ieaseMusic/resources/app.asar/main.js:234:159903)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:142126

关闭错误后所有图片均裂开。
oracle java 1.8

**Comment by trazyn** [comment]
10086 端口号被占用，设置里面可以重新设置端口号

**Comment by zhanjw** [comment]
sudo netstat -ant | grep 12306
tcp6       0      0 :::12306                :::*                    LISTEN     
tcp6       0      0 ::1:55378               ::1:12306               ESTABLISHED
tcp6       0      0 ::1:12306               ::1:55378               ESTABLISHED
12306是我改的端口
第一次进去的时候一直在圈圈滚动，没法进入任何页面
然后关闭程序再次打开的时候就提示端口占用（没有释放？）
然后能进去了，但是都裂开了。

**Comment by trazyn** [comment]
端口占用参考#40，hosts修改请参看#20
