### ISSUE TITLE
每次开启都会加载很长时间，然后弹出错误提示

### ISSUE THREAD

**Issue by zhangleijuly** [trazyn/ieaseMusic#61]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketOnEnd (_http_client.js:394:23)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by zhangleijuly** [comment]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:510:12)

**Comment by llllllligen** [comment]
我开始也这样过 把海外网易云代理那个的hosts删掉就正常了

**Comment by zhangleijuly** [comment]
怎么删除，实际上我在国内，只是用的英文版ubuntu，很多网站默认打开就是海外版的……

**Comment by Atomknight** [comment]
我也出现了这个问题，请问你解决了没？

**Comment by trazyn** [comment]
这个问题一般是被连接ban，可以试试换个hosts(#20)或者过重新打开试试

**Comment by zhangleijuly** [comment]
更换hosts没有解决问题。我在国内，应该没必要修改hosts。

**Comment by trazyn** [comment]
和国内国外无关，官方接口会在一定条件下触发限制，会在短时间内无法访问，比如高频访问

**Comment by zhangleijuly** [comment]
原来如此，现在的情况是这样的，我修改了hosts，把软件的端口修改到了1061，打开第一个播放器，会卡在加载界面，然后打开第二个播放器，会弹出一个错误提示框，内容如下，把提示框点掉之后两个播放器就都可以用了……
Uncaught Exception:
Error: listen EADDRINUSE :::1061
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at Function.j.listen (/opt/ieaseMusic/resources/app.asar/main.js:251:4482)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:124889
    at /opt/ieaseMusic/resources/app.asar/main.js:234:140845
    at i (/opt/ieaseMusic/resources/app.asar/main.js:234:159903)
    at /opt/ieaseMusic/resources/app.asar/main.js:234:142126

**Comment by zhangleijuly** [comment]
如果不打开第二个播放器就仍然是弹出两个socket hang up的错误提示，然后依然无限加载。

**Comment by trazyn** [comment]
打开两个肯定端口号就被占用了啊

**Comment by zhangleijuly** [comment]
嗯，但是据我尝试也只有打开多个实例才能使用了，不然无限加载停不下来……

**Comment by trazyn** [comment]
不用的 可以尝试打开devtools刷新试试
