### ISSUE TITLE
Arch Linux installation failed on invalid command `cross-env`

### ISSUE THREAD

**Issue by stardiviner** [trazyn/ieaseMusic#7]
Here is the log:
```
> iease-music@0.0.3 package-linux /home/user/Code/Linux/NetEase Music/ieaseMusic
> npm run build && rm -rf release && build --linux --projectDir ./dist


> iease-music@0.0.3 build /home/user/Code/Linux/NetEase Music/ieaseMusic
> rm -rf dist && npm run build-main && npm run build-renderer


> iease-music@0.0.3 build-main /home/user/Code/Linux/NetEase Music/ieaseMusic
> cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! iease-music@0.0.3 build-main: `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the iease-music@0.0.3 build-main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-09-28T01_53_11_016Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iease-music@0.0.3 build: `rm -rf dist && npm run build-main && npm run build-renderer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iease-music@0.0.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-09-28T01_53_11_144Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iease-music@0.0.3 package-linux: `npm run build && rm -rf release && build --linux --projectDir ./dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iease-music@0.0.3 package-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.3.0 → 5.4.2    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-09-28T01_53_11_237Z-debug.log
npm run package-linux  3.25s user 0.44s system 76% cpu 4.816 total
```

**Comment by trazyn** [comment]
it looks like have some troubles in your deps, you can run the bellow command to reinstall the deps
```
rm -rf node_modules
npm install
```

**Comment by stardiviner** [comment]
After your method. When I run command `npm run package-linux`, got error:
```
> uglifyjs-webpack-plugin@0.4.6 postinstall /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> electron@1.7.8 postinstall /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron
> node install.js

added 1160 packages in 96.097s
npm install  84.53s user 19.11s system 99% cpu 1:44.40 total

stardiviner@dark [ ~/Code/Linux/NetEase Music/ieaseMusic ] §
Ruby: {2.4.0-dev}, Python: [python3.6], Node: system, Java:
-----------
 ⇨  git:(⭠ master) (✓) npm run package-linux

> iease-music@0.0.3 package-linux /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic
> npm run build && rm -rf release && build --linux --projectDir ./dist


> iease-music@0.0.3 build /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic
> rm -rf dist && npm run build-main && npm run build-renderer


> iease-music@0.0.3 build-main /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic
> cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors

24559ms building modules
71ms sealing
5ms optimizing
0ms basic module optimization
8ms module optimization
3ms advanced module optimization
0ms basic chunk optimization
0ms chunk optimization
0ms advanced chunk optimization
4ms module and chunk tree optimization
0ms chunk modules optimization
1ms advanced chunk modules optimization
25ms module reviving
6ms module order optimization
12ms module id optimization
1ms chunk reviving
1ms chunk order optimization
70ms chunk id optimization
41ms hashing
1ms module assets processing
120ms chunk assets processing
9ms additional chunk assets processing
1ms recording
69861ms additional asset processing
1758ms chunk asset optimization
2ms asset optimization
218ms emitting
Hash: bc4ca961dcc1b4a1c085
Version: webpack 3.6.0
Time: 96830ms
      Asset     Size  Chunks                    Chunk Names
    main.js   459 kB       0  [emitted]  [big]  main
main.js.map  1.19 MB       0  [emitted]         main
 [186] multi babel-polyfill ./main.js 40 bytes {0} [built]
        factory:2ms building:6ms = 8ms
 [389] ./main.js 14 kB {0} [built]
       [] -> factory:356ms building:11517ms dependencies:8718ms = 20591ms
 [403] ./package.json 3.7 kB {0} [built]
       [] -> factory:8916ms building:15ms = 8931ms
 [404] ./config/index.js 625 bytes {0} [built]
       [] -> factory:8779ms building:368ms = 9147ms
 [405] ./server/api.js 8.78 kB {0} [built]
       [] -> factory:1249ms building:964ms dependencies:6566ms = 8779ms
 [425] ./node_modules/express/lib 160 bytes {0} [built]
       [] -> factory:123ms building:3ms = 126ms
 [438] (webpack)/buildin/module.js 517 bytes {0} [built]
       [] -> factory:228ms building:170ms = 398ms
 [480] ./server/api/hot_album.js 601 bytes {0} [built]
       [] -> factory:742ms building:3446ms dependencies:2379ms = 6567ms
 [481] ./server/router/home.js 20 kB {0} [built]
       [] -> factory:740ms building:4398ms dependencies:1429ms = 6567ms
 [485] ./server/router/player.js 19.3 kB {0} [built]
       [] -> factory:739ms building:3383ms dependencies:2450ms = 6572ms
 [486] ./server/router/user.js 6.47 kB {0} [built]
       [] -> factory:736ms building:1672ms dependencies:4159ms = 6567ms
 [487] ./server/router/artist.js 10.9 kB {0} [built]
       [] -> factory:734ms building:2278ms dependencies:3555ms = 6567ms
 [488] ./server/router/top.js 4.84 kB {0} [built]
       [] -> factory:732ms building:1284ms dependencies:4551ms = 6567ms
 [489] ./server/router/playlist.js 4.29 kB {0} [built]
       [] -> factory:728ms building:940ms dependencies:4899ms = 6567ms
 [490] ./server/router/fm.js 4.05 kB {0} [built]
       [] -> factory:479ms building:693ms = 1172ms
    + 476 hidden modules

WARNING in ./node_modules/express/lib/view.js
79:29-41 Critical dependency: the request of a dependency is an expression

ERROR in ./server/api/hot_album.js
Module not found: Error: Can't resolve '../../NeteaseCloudMusicApi/util/util' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server/api'
 @ ./server/api/hot_album.js 6:15-62
 @ ./server/api.js
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/album' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 41:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artist_album' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 47:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 44:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists_desc' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 50:24-78
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/artists_mv' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 53:22-74
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/banner' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 56:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/check_music' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 58:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_album' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 64:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_dj' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 71:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_like' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 69:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_music' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 60:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_mv' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 62:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/comment_playlist' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 66:29-87
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/daily_signin' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 74:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_catelist' in '/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/server'
 @ ./server/api.js 86:24-77
 @ ./main.js
 @ multi babel-polyfill
.....
```

**Comment by trazyn** [comment]
submodule is missing, thanks for your feedback, i will update it to readme
```
git submodule init
git submodule update
```

**Comment by stardiviner** [comment]
Seems Electron compilation requires `libreadline.so.6`, but my Arch Linux is using `libreadline.so.7`.
```
electron-builder 19.31.1
Installing app dependencies for arch x64 to /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/dist
Packaging for linux x64 using electron 1.7.6 to ../release/linux-unpacked
Building AppImage for arch x64
Error: Exit code: 127. Command failed: /home/stardiviner/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso -joliet on -volid AppImage -dev /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/release/iease-music-0.0.3-x86_64.AppImage -padding 0 -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/release/linux-unpacked /usr/bin -map /tmp/temp-files-lKDXes/1.sh /AppRun -map /tmp/temp-files-lKDXes/0-ieaseMusic.desktop /iease-music.desktop -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/128x128.png /usr/share/icons/default/128x128/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/16x16.png /usr/share/icons/default/16x16/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/24x24.png /usr/share/icons/default/24x24/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/32x32.png /usr/share/icons/default/32x32/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/48x48.png /usr/share/icons/default/48x48/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/64x64.png /usr/share/icons/default/64x64/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/96x96.png /usr/share/icons/default/96x96/apps/iease-music.png -map /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/resource/128x128.png /.DirIcon -map /home/stardiviner/.cache/electron-builder/appimage-packages/appimage-packages-25-09-17/x86_64-linux-gnu /usr/lib -chown_r 0 / -- -zisofs level=9:block_size=128k:by_magic=off set_filter_r --zisofs /
/home/stardiviner/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

/home/stardiviner/.cache/electron-builder/AppImage/AppImage-09-07-16-linux/xorriso: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory

    at /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/builder-util/src/util.ts:91:16
    at ChildProcess.exithandler (child_process.js:278:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at exec (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/builder-util/src/util.ts:63:3)
    at /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/src/targets/appImage.ts:99:5
    at Generator.next (<anonymous>)
From previous event:
    at AppImageTarget.build (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/out/targets/appImage.js:170:11)
    at taskManager.addTask.default.map.it (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/src/platformPackager.ts:110:85)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/src/platformPackager.ts:110:41)
    at /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/src/platformPackager.ts:106:10
From previous event:
    at LinuxPackager.pack (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/out/platformPackager.js:175:11)
    at /home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/home/stardiviner/Code/Linux/NetEase Music/ieaseMusic/node_modules/electron-builder
......
```

**Comment by trazyn** [comment]
Maybe u need upgrade the [readline package](https://www.archlinux.org/packages/core/i686/readline/)

**Comment by stardiviner** [comment]
Yes, my libreadline.so version is 7. But Electron compiles requires version 6.

**Comment by trazyn** [comment]
Try to create a soft link, libreadline.so.6 -> libreadline.so.7
