### ISSUE TITLE
ubuntu14.04 启动失败

### ISSUE THREAD

**Issue by howie6879** [trazyn/ieaseMusic#8]
报错信息：
``` shell
ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_recommend_type' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 94:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/dj_sub' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 84:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/event' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 97:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/fm_trash' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 100:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/follow' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 102:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/like' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 105:17-63
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/likelist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 107:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/logWeb' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 119:20-68
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/login' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 113:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/loginCellphone' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 110:28-84
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/login_refresh' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 116:58-113
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/lyric' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 122:18-65
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/musicUrl' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 125:22-72
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 134:15-59
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv_first' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 128:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/mv_url' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 131:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personal_fm' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 137:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 140:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_djprogram' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 143:35-99
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_mv' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 152:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_newsong' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 146:33-95
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/personalized_privatecontent' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 149:40-109
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_catlist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 162:29-87
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_detail' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 155:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_hot' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 160:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/playlist_tracks' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 158:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/program_recommend' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 165:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_dislike' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 174:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_resource' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 171:31-91
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/recommend_songs' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 168:28-85
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/resource_like' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 176:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 179:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search_multimatch' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 182:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/search_suggest' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 185:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_artists' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 200:24-78
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_mv' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 194:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_playlist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 188:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_song' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 191:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/simi_user' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 197:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/song_detail' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 203:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_album' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 206:22-73
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_artists' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 209:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_list' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 211:21-71
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_mv' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 213:19-67
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_playlist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 216:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_playlist_highquality' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 219:37-103
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/top_songs' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 221:21-72
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 223:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist_artist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 225:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/toplist_detail' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 227:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_audio' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 233:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_cloud' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 236:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_cloud_search' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 239:30-89
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_detail' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 244:24-77
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_dj' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 246:20-69
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_event' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 242:23-75
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_followeds' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 248:27-83
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_follows' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 250:25-79
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_playlist' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 230:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_playrecord' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 254:24-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

ERROR in ./server/api.js
Module not found: Error: Can't resolve '../NeteaseCloudMusicApi/router/user_subcount' in '/home/howie/Documents/programming/git/ieaseMusic/server'
 @ ./server/api.js 252:26-81
 @ ./main.js
 @ multi babel-polyfill ./main.js

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/node" "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/npm" "run" "build-main"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iease-music@0.0.3 build-main: `cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the iease-music@0.0.3 build-main script 'cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iease-music package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node -r babel-register ./node_modules/webpack/bin/webpack --config ./config/webpack.config.electron.js --progress --profile --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iease-music
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iease-music
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/howie/Documents/programming/git/ieaseMusic/npm-debug.log

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/node" "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/npm" "run" "build"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iease-music@0.0.3 build: `rm -rf dist && npm run build-main && npm run build-renderer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iease-music@0.0.3 build script 'rm -rf dist && npm run build-main && npm run build-renderer'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iease-music package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rm -rf dist && npm run build-main && npm run build-renderer
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iease-music
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iease-music
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/howie/Documents/programming/git/ieaseMusic/npm-debug.log

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/node" "/home/howie/Documents/programming/git/nvm/versions/node/v6.11.3/bin/npm" "run" "package-linux"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iease-music@0.0.3 package-linux: `npm run build && rm -rf release && build --linux --projectDir ./dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iease-music@0.0.3 package-linux script 'npm run build && rm -rf release && build --linux --projectDir ./dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iease-music package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && rm -rf release && build --linux --projectDir ./dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iease-music
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iease-music
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/howie/Documents/programming/git/ieaseMusic/npm-debug.log
``` 
[npm-debug.log](https://github.com/trazyn/ieaseMusic/files/1339347/npm-debug.log)

**Comment by trazyn** [comment]
子模块缺失，然后就没问题了，等下更下到readme
```
git submodule init
git submodule update
```

**Comment by howie6879** [comment]
打包好了 启动报这个错：
``` shell
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'setIcon' of undefined
    at Object.<anonymous> (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:222:121964)
    at a (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:1:256)
    at Object.<anonymous> (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:222:67043)
    at a (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:1:256)
    at /tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:1:616
    at Object.<anonymous> (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:1:628)
    at Object.<anonymous> (/tmp/.mount_92CwKB/usr/bin/resources/app.asar/main.js:408:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

**Comment by trazyn** [comment]
你把`main.js` 520 行的 `app.dock.setIcon(`${__dirname}/src/assets/dock.png`);` 注释看看，还有没啥不兼容的

**Comment by howie6879** [comment]
注释掉后 我运行  npm run dev
能打开 但是根本点不动 就自动播放一首电子乐
托盘图标可以上一首 界面基本点不动 无反应

**Comment by trazyn** [comment]
没有linux 😕 你打开dev tool 然后刷新截图给我看看

**Comment by howie6879** [comment]
截哪部分给你看？  就是界面只能看不能点 是不是路径问题？

**Comment by trazyn** [comment]
把network 界面还有控制台的都截图了 我来看看

**Comment by howie6879** [comment]
![selection_006](https://user-images.githubusercontent.com/17047388/30954228-fccb0c46-a461-11e7-99b7-1d973ec4e09c.png)
![selection_007](https://user-images.githubusercontent.com/17047388/30954229-fccc572c-a461-11e7-9381-9bd55e1c559d.png)
![selection_008](https://user-images.githubusercontent.com/17047388/30954230-fcfe1820-a461-11e7-9f32-2d56fd4364fb.png)

**Comment by trazyn** [comment]
界面部分看起来是没报错的，控制台的打印也是ok的
界面上那几个小图标不能点击还有歌单也不能滚动么

**Comment by trazyn** [comment]
我装个linux看看吧

**Comment by howie6879** [comment]
好的 麻烦了  我是Ubuntu14.04

**Comment by trazyn** [comment]
嗯知道了

**Comment by succlz123** [comment]
同样这个问题 dev tool 能点击,其他界面点击无效, 点击以后鼠标变成拖动标志
electron 1.6.11 manjaro linux

**Comment by trazyn** [comment]
嗯在装Ubuntu中

**Comment by trazyn** [comment]
![screen shot 2017-09-28 at 8 53 08 pm](https://user-images.githubusercontent.com/1774898/30967503-1049977e-a48f-11e7-9a8e-5bd8f4e12580.png)
用刚装好的Ubuntu事了下，感觉字体有些奇怪啊

**Comment by trazyn** [comment]
![screen shot 2017-09-28 at 8 55 36 pm](https://user-images.githubusercontent.com/1774898/30967600-65f8b3bc-a48f-11e7-91fe-dfee6003d2d1.png)
我感觉我是不是要加个功能给你们自己去改字体啊:doge:

**Comment by howie6879** [comment]
可以加个功能改字体:smile:

**Comment by howie6879** [comment]
再有个bug 当一首歌暂停一段时间 就没法继续播放～～

**Comment by trazyn** [comment]
@howie6879 界面上基本都是横向滚动的，不是传统的竖着滚动。所以你姿势不对了😂 歌曲都是有时效性的，时间久了就过期了

**Comment by howie6879** [comment]
那linux怎么滑。。加个横条么。。

**Comment by trazyn** [comment]
鼠标直接滚动就行啊

**Comment by howie6879** [comment]
歌曲那个不能先缓存到本地么？

**Comment by trazyn** [comment]
进度条后面的那个就是缓冲进度，很极端的情况下才会出现时效性问题导致播放失败，没显示的字体是emoji，linux下默认emoji很low，黑白还有很多就没有，换个兼容的字库就有了
