### ISSUE TITLE
can't start in Archlinux-Based system

### ISSUE THREAD

**Issue by ZhengshuaiPENG** [trazyn/ieaseMusic#92]
Hello, 
I use Manjaro Linux(Archlinux based), and installed iease-music from Archlinux CN repo.
But when I open it, it throws an exception like below

`➜  ~ iease-music
App threw an error during load
/opt/ieaseMusic/main.js:2
import { app, BrowserWindow, Menu, Tray, globalShortcut, ipcMain, shell, powerMonitor } from 'electron';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:361:3)
    at Module._compile (module.js:571:32)
A JavaScript error occurred in the main process
Uncaught Exception:
/opt/ieaseMusic/main.js:2
import { app, BrowserWindow, Menu, Tray, globalShortcut, ipcMain, shell, powerMonitor } from 'electron';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (/usr/lib/electron/resources/default_app.asar/main.js:283:12)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:325:5)
    at Object.<anonymous> (/usr/lib/electron/resources/default_app.asar/main.js:361:3)
    at Module._compile (module.js:571:32)
^C%                                                                             ➜  ~ 
`

So If there is some dependencies missing?

**Comment by trazyn** [comment]
Maybe you should download the [`AppImage`](https://github.com/trazyn/ieaseMusic/releases)
